FROM python

COPY requirements.txt .
COPY almost-final-edit.py .
ADD train_dir.tar /train_dir

RUN pip install cmake
RUN pip install dlib
RUN pip install -r requirements.txt

CMD ["python","almost-final-edit.py"]