apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: mysql-service
  namespace: face
spec:
  type: ClusterIP
  ports:
  - name: "db-service"
    port: 3306
    targetPort: 3306
  selector:
    app: db
